name: .NET Core

on:
  push:
    branches: [ TemporaryNuget ]
  pull_request:	
    branches: [ TemporaryNuget ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -o ./output ./Orleans.Sagas
    - name: Add nuget registry
      run: dotnet nuget add source --username LodeKennes --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NAMESPACE/index.json"
    - name: Push
      run: dotnet nuget push ./output/*.nupkg --source github
